services:
  hoops-vs-beans-api:
    build:
      context: .
      dockerfile: HoopsVsBeans.Dockerfile
    container_name: hoops-vs-beans_api
    labels: []
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/tmp/HoopsVsBeans.db